##
# L`algorithme de Djikstra
#
# @file
# @version 0.1

dijkstra_des_zero.pdf:  biblio.bib algo_dijkstra.tex complexite.tex dijkstra_des_zero.tex theorie_des_graphes.tex
	pdflatex dijkstra_des_zero.tex
	bibtex dijkstra_des_zero.aux
	pdflatex dijkstra_des_zero.tex
	pdflatex dijkstra_des_zero.tex



# end
